# Generated by Django 2.2.4 on 2020-04-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_votes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Answer',
        ),
    ]
